### ISSUE TITLE
An error of TypeError while running LJSpeech-1.1

### ISSUE THREAD

**Issue by ghost** [Kyubyong/expressive_tacotron#2]
Thanks for your contribution. :+1: 

I follow the steps of Training: Run python train.py.

However, I got this error: :(
  0%|                                          | 0/409 [00:00<?, ?b/s]2018-04-08 11:58:13.819432:
W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: TypeError: a bytes-like object is required, not 'str'

**Comment by reidsanders** [comment]
A simple (though not optimal) solution is to use python 2.

**Comment by ghost** [comment]
thanks @reidsanders :) I miss the first line:
#/usr/bin/python2 :(
